image: atlassian/default-image:2

pipelines:
    pull-requests:
        '**':
            -   step:
                    name: Lint php
                    image: php:7.2
                    script:
                        - apt-get update && apt-get install -y unzip
                        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                        - composer install
                        - composer run php-lint
