services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $clientsRepository: '@heptacom_admin_open_auth_client.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $loginsRepository: '@heptacom_admin_open_auth_login.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $userEmailsRepository: '@heptacom_admin_open_auth_user_email.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $userKeysRepository: '@heptacom_admin_open_auth_user_key.repository'

    _instanceof:
        Heptacom\AdminOpenAuth\Contract\ProviderInterface:
            tags:
                - 'heptacom_admin_opean_auth.client_provider'

    Heptacom\AdminOpenAuth\:
        resource: '../../*'
        exclude:
            - '../../Database/*Collection.php'
            - '../../Database/*Entity.php'
            - '../../Exception/*'
            - '../../Migration/*'
            - '../../Resources/*'

    Heptacom\AdminOpenAuth\Database\ClientDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_client' }
    Heptacom\AdminOpenAuth\Database\LoginDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_login' }
    Heptacom\AdminOpenAuth\Database\UserEmailDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_email' }
    Heptacom\AdminOpenAuth\Database\UserKeyDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_key' }

    Heptacom\AdminOpenAuth\ClientLoader:
        arguments:
            - !tagged_iterator heptacom_admin_opean_auth.client_provider
