services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $clientsRepository: '@heptacom_admin_open_auth_client.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $loginsRepository: '@heptacom_admin_open_auth_login.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $userEmailsRepository: '@heptacom_admin_open_auth_user_email.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $userKeysRepository: '@heptacom_admin_open_auth_user_key.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface $userTokensRepository: '@heptacom_admin_open_auth_user_token.repository'
            Psr\Http\Client\ClientInterface $oidcHttpClient: '@heptacom.admin_open_auth.oidc.http_client'

    _instanceof:
        Heptacom\OpenAuth\ClientProvider\Contract\ClientProviderContract:
            tags:
                - 'heptacom_open_auth.client_provider'
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags:
                - 'kernel.event_subscriber'

    Heptacom\AdminOpenAuth\:
        resource: '../../*'
        exclude:
            - '../../Database/*Collection.php'
            - '../../Database/*Entity.php'
            - '../../Exception/*'
            - '../../Migration/*'
            - '../../Resources/*'

    heptacom.admin_open_auth.oidc.http_client:
        class: 'GuzzleHttp\Client'
        arguments:
            - protocols: [https]
              verify: true
              timeout: 15
              headers:
                  Accept: application/json

    Heptacom\AdminOpenAuth\Component\OpenIdConnect\OpenIdConnectService:
        arguments:
            - '@heptacom.admin_open_auth.http_client'

    Heptacom\AdminOpenAuth\Database\ClientDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_client' }
    Heptacom\AdminOpenAuth\Database\LoginDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_login' }
    Heptacom\AdminOpenAuth\Database\UserEmailDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_email' }
    Heptacom\AdminOpenAuth\Database\UserKeyDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_key' }
    Heptacom\AdminOpenAuth\Database\UserTokenDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_token' }

    Heptacom\AdminOpenAuth\Service\OpenAuth\OneTimeTokenClientRepository:
        decorates: Shopware\Core\Framework\Api\OAuth\ClientRepository
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\OpenAuth\OneTimeTokenClientRepository.inner'

    Heptacom\AdminOpenAuth\Service\Provider\JiraClientEntityRepository:
        decorates: heptacom_admin_open_auth_client.repository
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\JiraClientEntityRepository.inner'

    Heptacom\AdminOpenAuth\Service\Provider\MicrosoftAzureClientEntityRepository:
        decorates: heptacom_admin_open_auth_client.repository
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\MicrosoftAzureClientEntityRepository.inner'

    Heptacom\AdminOpenAuth\Service\Provider\OpenIdConnectClientEntityRepository:
        decorates: heptacom_admin_open_auth_client.repository
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\OpenIdConnectClientEntityRepository.inner'

    Heptacom\AdminOpenAuth\OpenAuth\OneTimeTokenScopeRepository:
        decorates: Shopware\Core\Framework\Api\OAuth\ScopeRepository
        arguments:
            - '@Heptacom\AdminOpenAuth\OpenAuth\OneTimeTokenScopeRepository.inner'

    Heptacom\AdminOpenAuth\Subscriber\ApiAuthentication:
        arguments:
            - '@shopware.api.authorization_server'
            - '@Shopware\Core\Framework\Api\OAuth\UserRepository'
            - '@Shopware\Core\Framework\Api\OAuth\RefreshTokenRepository'

    Heptacom\AdminOpenAuth\Service\UserResolver:
        arguments:
            - '@user.repository'
