services:
    Heptacom\OpenAuth\Client\Contract\TokenPairFactoryContract: ~

    Heptacom\OpenAuth\Client\Contract\ClientFactoryContract:
        arguments:
            - '@Heptacom\OpenAuth\ClientProvider\Contract\ClientProviderRepositoryContract'

    Heptacom\OpenAuth\ClientProvider\Contract\ClientProviderRepositoryContract:
        arguments:
            - !tagged_iterator heptacom_open_auth.client_provider
